name: Build and publish serverless function

on:
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # nodig om commando's te kunnen uitvoeren
      - name: Download and install faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh
      # vereist om Docker images te kunnen bouwen
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: vincentnys
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login faasd
        run: faas-cli login -u admin --password ${{ secrets.FAASD_PASSWORD }} --gateway https://jaws2paws.com
      - name: Build and publish function
        run: faas-cli up -f greyscaled2.yml
      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          from-email: cloudsystemen2024@gmail.com
          to-email: cloudsystemen2024@gmail.com
          username: cloudsystemen2024@gmail.com
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
            <h1>This is a test email</h1>
            <p>Test Paragraph</p>
